--
-- Файл сгенерирован с помощью SQLiteStudio v3.2.1 в Ср авг 19 02:26:26 2026
--
-- Использованная кодировка текста: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: MY_BREED
CREATE TABLE MY_BREED (BRE_ID INTEGER PRIMARY KEY, BRE_NAME VARCHAR (50) UNIQUE, BRE_INFO VARCHAR (1000));

-- Таблица: MY_CFG
CREATE TABLE MY_CFG (CFG_ID INTEGER PRIMARY KEY NOT NULL, CFG_NAME VARCHAR (15) UNIQUE, CFG_VALUE VARCHAR (50), CFG_INFO VARCHAR (150));

-- Таблица: MY_COLOR
CREATE TABLE MY_COLOR (COL_ID INTEGER PRIMARY KEY, COL_NAME VARCHAR (30), COL_TAG INTEGER);

-- Таблица: MY_CURE
CREATE TABLE MY_CURE (CUR_ID INTEGER PRIMARY KEY, CUR_DATE DATE, CUR_HIVE_ID INTEGER, CUR_CURE_TYPE INTEGER, CUR_INFO VARCHAR (1000), CUR_RESULT VARCHAR (1000));

-- Таблица: MY_EVENT
CREATE TABLE MY_EVENT (EVN_ID INTEGER PRIMARY KEY, EVN_HIVE_ID INTEGER, EVN_DATE VARCHAR (10), EVN_INFO VARCHAR (1000));

-- Таблица: MY_FAMILY
CREATE TABLE MY_FAMILY (FAM_ID INTEGER PRIMARY KEY, FAM_BREED_TYPE INTEGER, FAM_HIVE_ID INTEGER, FAM_NAME VARCHAR (50), FAM_LEVEL INTEGER, FAM_DATE_START DATE (10), FAM_DATE_END DATE (10), FAM_INFO VARCHAR (1000));

-- Таблица: MY_FIELDS
CREATE TABLE MY_FIELDS (FLD_TABLE VARCHAR (30), FLD_NAME VARCHAR (30), FLD_INFO VARCHAR (150));

-- Таблица: MY_FRAME
CREATE TABLE MY_FRAME (FRM_ID INTEGER PRIMARY KEY, FRM_NAME VARCHAR (50), FRM_MATERIAL INTEGER, FRM_HEIGHT INTEGER, FRM_WIDTH INTEGER, FRM_INFO VARCHAR (100));

-- Таблица: MY_HIVE
CREATE TABLE MY_HIVE (HIV_ID INTEGER PRIMARY KEY, HIV_NUMB INTEGER UNIQUE, HIV_TYPE INTEGER, HIV_NAME VARCHAR (30), HIV_INFO VARCHAR (50), HIV_POS VARCHAR (200), HIV_COLOR VARCHAR (30), HIV_STATUS INTEGER, HIV_ADD VARCHAR (30));

-- Таблица: MY_INSPECT
CREATE TABLE MY_INSPECT (INS_ID INTEGER PRIMARY KEY, INS_DATE DATE (10), INS_HIVE_ID INTEGER, INS_PCHUL INTEGER, INS_RAMALL INTEGER, INS_RAMRAS INTEGER, INS_RAMVOS INTEGER, INS_VESMED INTEGER, INS_RESULT VARCHAR (1000));

-- Таблица: MY_MATERIAL
CREATE TABLE MY_MATERIAL (MAT_ID INTEGER PRIMARY KEY, MAT_NAME VARCHAR (50), MAT_INFO VARCHAR (100));

-- Таблица: MY_STATUS
CREATE TABLE MY_STATUS (STA_ID INTEGER PRIMARY KEY, STA_NAME VARCHAR (20), STA_TAG INTEGER);

-- Таблица: MY_TABLES
CREATE TABLE MY_TABLES (TAB_NAME VARCHAR (30) PRIMARY KEY, TAB_INFO VARCHAR (100));

-- Таблица: MY_TASK
CREATE TABLE MY_TASK (TAS_ID integer PRIMARY KEY, TAS_HIVE_ID integer, TAS_INFO VARCHAR (150), TAS_END boolean, TAS_DATE DATE, TAS_REZ VARCHAR (50));

-- Таблица: MY_TYPE_CURE
CREATE TABLE MY_TYPE_CURE (TCU_ID INTEGER PRIMARY KEY, TCU_NAME VARCHAR (50), TCU_INFO VARCHAR (1000));

-- Таблица: MY_TYPE_HIVE
CREATE TABLE MY_TYPE_HIVE (TYP_ID INTEGER PRIMARY KEY, TYP_NAME VARCHAR (50) UNIQUE, TYP_MATERIAL INTEGER, TYP_FRAME_TYPE INTEGER, TYP_FRAME_COUNT INTEGER, TYP_INFO VARCHAR (100));

-- Таблица: MY_TYPE_ILL
CREATE TABLE MY_TYPE_ILL (ILL_ID INTEGER PRIMARY KEY, ILL_NAME VARCHAR (50), ILL_INFO VARCHAR (200));

-- Таблица: SQLitePass__DbSettings
CREATE TABLE "SQLitePass__DbSettings" ("StorageVersion" __memo, "MainProperties" __memo, "TranslationRules" __memo, "CustomFieldDefs" __memo);

-- Индекс: idx_MY_CURE_
CREATE INDEX idx_MY_CURE_ ON MY_CURE ("CUR_HIVE_ID");

-- Индекс: idx_MY_CURE_2
CREATE INDEX idx_MY_CURE_2 ON MY_CURE ("CUR_DATE");

-- Индекс: idx_MY_EVENT_
CREATE INDEX idx_MY_EVENT_ ON MY_EVENT ("EVN_HIVE_ID");

-- Индекс: idx_MY_EVENT_2
CREATE INDEX idx_MY_EVENT_2 ON MY_EVENT ("EVN_DATE");

-- Индекс: idx_MY_INSPECT_
CREATE INDEX idx_MY_INSPECT_ ON MY_INSPECT ("INS_HIVE_ID");

-- Индекс: idx_MY_INSPECT_2
CREATE INDEX idx_MY_INSPECT_2 ON MY_INSPECT ("INS_DATE");

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
